version: '3.5'

services:
  ## INITIALIZE GENESIS AND SECRETS
  init:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    command: ["init"]
    volumes:
      - node-1:/exzocoin/data-1
      - node-2:/exzocoin/data-2
      - node-3:/exzocoin/data-3
      - node-4:/exzocoin/data-4
      - genesis:/genesis
    networks:
      - exzocoin-docker
  
  ## RUN NODES
  ## Nodes must have the same names as folders in genesis-legde
  node-1:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    command: ["server", "--data-dir", "/data", "--chain", "/genesis/genesis.json", "--grpc-address", "0.0.0.0:9632", "--libp2p", "0.0.0.0:1478", "--jsonrpc", "0.0.0.0:8545", "--prometheus", "0.0.0.0:5001", "--seal"]
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - '10000:9632'
      - '10002:8545'
      - '10003:5001'
    volumes:
      - node-1:/data
      - genesis:/genesis
    networks:
      - exzocoin-docker
    restart: on-failure
    
  node-2:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    command: ["server", "--data-dir", "/data", "--chain", "/genesis/genesis.json", "--grpc-address", "0.0.0.0:9632", "--libp2p", "0.0.0.0:1478", "--jsonrpc", "0.0.0.0:8545", "--prometheus", "0.0.0.0:5001", "--seal"]
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - '20000:9632'
      - '20002:8545'
      - '20003:5001'
    volumes:
      - node-2:/data
      - genesis:/genesis
    networks:
      - exzocoin-docker
    restart: on-failure
    
  node-3:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    command: ["server", "--data-dir", "/data", "--chain", "/genesis/genesis.json", "--grpc-address", "0.0.0.0:9632", "--libp2p", "0.0.0.0:1478", "--jsonrpc", "0.0.0.0:8545", "--prometheus", "0.0.0.0:5001", "--seal"]
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - '30000:9632'
      - '30002:8545'
      - '30003:5001'
    volumes:
      - node-3:/data
      - genesis:/genesis
    networks:
      - exzocoin-docker
    restart: on-failure
    
  node-4:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    command: ["server", "--data-dir", "/data", "--chain", "/genesis/genesis.json", "--grpc-address", "0.0.0.0:9632", "--libp2p", "0.0.0.0:1478", "--jsonrpc", "0.0.0.0:8545", "--prometheus", "0.0.0.0:5001", "--seal"]
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - '40000:9632'
      - '40002:8545'
      - '40003:5001'
    volumes:
      - node-4:/data
      - genesis:/genesis
    networks:
      - exzocoin-docker
    restart: on-failure

networks:
  exzocoin-docker:
    driver: bridge
    name: exzocoin-docker

volumes:
  node-1:
  node-2:
  node-3:
  node-4:
  genesis:
